<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TrayVoha</AssemblyName>
    <RootNamespace>TrayVoha</RootNamespace>
    <Product>TrayVoha</Product>
    <Description>Сповіщення про повітряні тривоги для вибраних територій України</Description>
    <Version>1.3.8</Version>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationIcon Condition="Exists('assets\windows\trayvoha.ico')">assets\windows\trayvoha.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
