<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Тривога</AssemblyName>
    <RootNamespace>Tryvoha</RootNamespace>
    <Version>1.4.4</Version>
    <Authors>yurko-kuro</Authors>
    <Description>Повітряні тривоги для вибраних районів та областей України.</Description>
    <RepositoryUrl>https://github.com/yurko-kuro/tryvoha-desktop</RepositoryUrl>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
